In [3]:
!pip install tensorflow

  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
  Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
  Using cached tensorboard_data_server-0.6.1-py3-none-any.whl (2.4 kB)
  Using cached google_auth_oauthlib-0.4.6-py2.py3-none-any.whl (18 kB)
  Using cached tensorboard_plugin_wit-1.8.1-py3-none-any.whl (781 kB)
  Using cached pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
  Using cached requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
  Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
  Attempting uninstall: importlib-metadata
    Found existing installation: importlib-metadata 3.10.0
    Uninstalling importlib-metadata-3.10.0:
      Successfully uninstalled importlib-metadata-3.10.0


In [4]:
import numpy as np
import pandas as pd
import tensorflow as tf

# Data preprocessing 

In [7]:
# importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [8]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [9]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [10]:
print(y)

[1 0 1 ... 1 1 0]


In [11]:
# encoding categorical data 
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [12]:
# splitting 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [13]:
# feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Building the ANN

In [18]:
# Initialising the ANN
ann = tf.keras.models.Sequential()

In [19]:
# Adding input layer and hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [20]:
# Adding second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [21]:
# Adding output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Training the ANN

In [24]:
# Compiling the ann 
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [25]:
# Training the ann on training set
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 3s 1ms/step - loss: 0.5960 - accuracy: 0.7264
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4788 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4477 - accuracy: 0.8041
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4335 - accuracy: 0.8129
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4240 - accuracy: 0.8179
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4144 - accuracy: 0.8206
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4051 - accuracy: 0.8265
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3964 - accuracy: 0.8316
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3882 - accuracy: 0.8356
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3799 - accura

250/250 [==============================] - 0s 1ms/step - loss: 0.3344 - accuracy: 0.8619
Epoch 82/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3342 - accuracy: 0.8612
Epoch 83/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3344 - accuracy: 0.8639
Epoch 84/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3341 - accuracy: 0.8643
Epoch 85/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3340 - accuracy: 0.8637
Epoch 86/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3342 - accuracy: 0.8629
Epoch 87/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3342 - accuracy: 0.8637
Epoch 88/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3339 - accuracy: 0.8639
Epoch 89/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3338 - accuracy: 0.8644
Epoch 90/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3346 - accuracy: 

# Making the predictions and evaluating the model

In [26]:
""" Use our ANN model to predict if the customer with the following informations will leave the bank:
Geography: France
Credit Score: 600
Gender: Male
Age: 40 years old
Tenure: 3 years
Balance: $ 60000
Number of Products: 2
Does this customer have a credit card? Yes
Is this customer an Active Member: Yes
Estimated Salary: $ 50000
So, should we say goodbye to that customer? """

print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 2s 2s/step
[[0.04156796]]
1/1 [==============================] - 0s 22ms/step
[[False]]


In [27]:
"""
Therefore, our ANN model predicts that this customer stays in the bank!
Important note 1: Notice that the values of the features were all input in a double pair of square brackets. 
That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values 
into a double pair of square brackets makes the input exactly a 2D array.

Important note 2: Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in 
the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, 
and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include 
these values in the first three columns, because the dummy variables are always created in the first columns.
"""

'\nTherefore, our ANN model predicts that this customer stays in the bank!\nImportant note 1: Notice that the values of the features were all input in a double pair of square brackets. \nThat\'s because the "predict" method always expects a 2D array as the format of its inputs. And putting our values \ninto a double pair of square brackets makes the input exactly a 2D array.\n\nImportant note 2: Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in \nthe first three columns. That\'s because of course the predict method expects the one-hot-encoded values of the state, \nand as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include \nthese values in the first three columns, because the dummy variables are always created in the first columns.\n'

In [28]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [29]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1506   89]
 [ 190  215]]


0.8605